### ISSUE TITLE
Still using my google analytics tag

### ISSUE THREAD

**Issue by MikhaD** [bennw/werdel#1]
Hi, I like what you have done with this. Could you possibly remove the google analytics script from the header? People are playing your game and contributing to my analytics.
![image](https://user-images.githubusercontent.com/31388146/161781578-b65bd931-c505-46df-9a77-1e79fefc37a0.png)

**Comment by bennw** [comment]
My sincere apologies for taking so long to rectify this - completely wasn't notified of this. I hope this hasn't caused you too much trouble; do let me know if it's still not fixed or if my app is still causing inconvenience. Thanks again for the wonderful work you did on this!
